// <auto-generated />
using System;
using EventServe.SqlStreamStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventServe.SqlStreamStore.MsSql.Migrations
{
    [DbContext(typeof(SqlStreamStoreContext))]
    [Migration("20200222150924_RemoveNameFromSubscriptionPosition")]
    partial class RemoveNameFromSubscriptionPosition
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventServe.SqlStreamStore.Subscriptions.PeristentSubscriptionPosition", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("SubscriptionId");

                    b.ToTable("SubscriptionPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
